require('modules.plugins.packer')
require('modules.plugins.cmp')
require('modules.plugins.treesitter')
require('modules.plugins.telescope')
require('modules.plugins.fugitive')
require('modules.plugins.lualine')
require('modules.plugins.devicons')
